### ISSUE TITLE
Internal Server Error on preview

### ISSUE THREAD

**Issue by iLikeKoffee** [klen/django_markdown#54]
Hello, I tried to install this library on Django 1.9 and got such error in admin interface when tried to run preview.

```
Internal Server Error: /markdown/preview/
Traceback (most recent call last):
  File "/home/alexey/Dev/profcom/django-rest-env/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/alexey/Dev/profcom/django-rest-env/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alexey/Dev/profcom/django-rest-env/lib/python3.4/site-packages/django_markdown/views.py", line 22, in preview
    content=request.REQUEST.get('data', 'No content posted'),
AttributeError: 'WSGIRequest' object has no attribute 'REQUEST'
[10/Dec/2015 22:14:47] "POST /markdown/preview/ HTTP/1.1" 500 14951
```

Here is the model code

```
class Post(models.Model):
    name = models.CharField(max_length=50, null=False, primary_key=True)  # Name for human-readable url
    title = models.CharField(max_length=255, null=False, unique=True)  # Human-readable title
    text = MarkdownField()  # Text in markdown syntax
    documents = models.ManyToManyField('Document', blank=True)
    commission = models.ForeignKey('Commission', related_name="posts")
    pinned = models.BooleanField(default=False)  # Should display on main
    date = models.DateTimeField(auto_now=True)
    image = models.FileField(upload_to='post_tiles', null=True)
```

Is it compatible with django 1.9?
Thank you in advance!

Sinclerely, Alexey
##

**Comment by noisytoken** [comment]
I am facing the same issue.

**Comment by macskay** [comment]
Someone opened a PR (#60) about this. Until it is not merged just alter your views.py of django_markdown. Worked for me perfectly.

**Comment by jarifibrahim** [comment]
`request.REQUEST` was deprecated in Django 1.7, and removed in Django 1.9.

Open the file `views.py` inside `django_markdown` folder and go to line 22, and change the following line

`content=request.REQUEST.get('data', 'No content posted')`

to

`content=request.POST.get('data', 'No content posted')`
